# Generated by Django 6.0.2 on 2026-02-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0002_resumescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumescore',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='resumechecker.jobdescription'),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='resumechecker.resume'),
        ),
    ]
